---
title: "Replication of Repeat after us: Syntactic alignment is not partner-specific by Rachel Ostrand and V.S. Ferreira (2019, Psychological Science)"
author: "A.J. Schwartz (avschwartz@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

 This experiment was chosen based on my current research interest in conversational alignment in psycholinguistics. In short, the experiment tests whether or not speakers align linguistically to their specific conversation partner as compared with a more general alignment towards what they have recently been exposed to. My past research, while being psycholinguistic in nature, was not focused on conversation, but moreseo on learning. This project will hopefully encourage my reading and exploration on syntactic alignment. This specific paper was produced partially by Dr. Ferreira's lab, which I am working in, so I will have access to people who are familiar with the data and the background of the study. Additionally, I have very little familiarity with analyzing psycholinguistic data, in my undergrad the experiment I conducted required more analysis of cognitive test results. I hope to do the computational reproducibility project over the replication project, because I believe that hands on experience with data analysis is more important to my studies than learning something like jspsych, especially because much of my experimentation happens in person- and because I have access to data that is very much like what I would want to be collecting for this experiment, without having to take the many hours it takes to transcribe recording data. 
  
|  While there is access to data, I have no access to the code used to run the analyses or create the figures. For this project, I hope to reproduce the findings of experiment 4 and 5, which I consider to be the most important experiments from the paper. Experiment 4 eliminates some of the issues in the previous 3 and demonstrates a lack of partner-specific alignment. Experiment 5 takes that even further and shows a lack of partner alignment even when the partner may not understand other syntactical structures. I hope to produce a 4 (Syntax Exposure Condition: all-Prepositional Dative, speaker-specific, mixed, all-Double Object) × 2 (Listener: Experimenter A, Experimenter B) GLMM model for experiment for with a sub-model to test each of the single structure alignments against each other and a sub-model to test the speaker-specific and mixed conditions against each other. I will be doing the same analysis for experiment five as well. Each model will contain a visualization, including the sub-models, which do not have visualaztions in the paper that this will be based off. I hope to gain some experience with ggplot- I have a strong background in design, and an interest in data visualization generally, but no hands on experience with it. The main challenge will be working with linguistic instead of numerical data, and figuring out how to translate transcribed sentences into data. I also would like to take some time to make the visualizations not only legible, but visually appealing. In the past, I've relied on programs like JASP and Jamovi to analyze my data for me, but I think it'll be important to learn how to do that in base R considering the limitations of softwares like those. 


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
